version: "3.3"
services:
  ring-motion-sensor:
    build: .
    network_mode: host # Required for hue hub connectivity
    environment:
      HUE_USERNAME: $HUE_USERNAME
      HUE_CLIENT_KEY: $HUE_CLIENT_KEY
      HUE_LIGHTS: $HUE_LIGHTS
      RING_REFRESH_TOKEN: $RING_REFRESH_TOKEN
      RING_CAMERA_NAME: $RING_CAMERA_NAME
      LIGHT_ON_TIME: $LIGHT_ON_TIME
      LATITUDE: $LATITUDE
      LONGITUDE: $LONGITUDE
